safe_ai:
  target: prod
  outputs:
    prod:
      type: duckdb
      path: "md:my_db"
      extensions:
        - motherduck
    dev:
      type: duckdb
      path: "/Users/lubospernis/Documents/safe_ai/dev.duckdb"
      schema: main_safe
