"""Send the report notification email via Gmail SMTP."""

from __future__ import annotations

import os
import smtplib
from email.message import EmailMessage


_SENDER = "lubos.pernis@gmail.com"
_SMTP_HOST = "smtp.gmail.com"
_SMTP_PORT = 587


def send_report_email(
    recipients: list[str],
    wave_label: str,
    executive_summary: str,
    pages_url: str,
    final_score: float,
    iterations: int,
) -> None:
    password = os.environ.get("GMAIL_APP_PASSWORD", "")
    if not password:
        print("[email] GMAIL_APP_PASSWORD not set — skipping email.")
        return

    subject = f"SAFE Slovakia Report — {wave_label}"

    body_text = f"""New ECB SAFE Slovakia analysis published for {wave_label}.

View full report: {pages_url}

--- Executive Summary ---
{executive_summary}

--- Report Metadata ---
Self-correction iterations: {iterations}
Final LLM judge score: {final_score:.0%}

---
Generated by SAFE Agent. Data source: ECB SAFE microdata via MotherDuck.
"""

    body_html = f"""<html><body>
<p>New ECB SAFE Slovakia analysis published for <strong>{wave_label}</strong>.</p>
<p><a href="{pages_url}">View full report →</a></p>
<h3>Executive Summary</h3>
<p>{executive_summary.replace(chr(10), '<br>')}</p>
<hr>
<p style="font-size:0.85em;color:#666;">
  Self-correction iterations: {iterations} &nbsp;|&nbsp;
  LLM judge score: {final_score:.0%}<br>
  Generated by SAFE Agent. Data: ECB SAFE microdata via MotherDuck.
</p>
</body></html>"""

    msg = EmailMessage()
    msg["Subject"] = subject
    msg["From"] = _SENDER
    msg["To"] = ", ".join(recipients)
    msg.set_content(body_text)
    msg.add_alternative(body_html, subtype="html")

    with smtplib.SMTP(_SMTP_HOST, _SMTP_PORT) as smtp:
        smtp.ehlo()
        smtp.starttls()
        smtp.login(_SENDER, password)
        smtp.send_message(msg)

    print(f"[email] sent to {recipients}")
