{{
  config(
    materialized = 'view'
  )
}}

with source as (

    select * from {{ source('raw', 'safe_microdata') }}

),

staged as (

    select

        --------------------------------------------------------------------------
        -- IDENTIFIERS
        --------------------------------------------------------------------------
        permid,
        wave::integer                                               as wave_number,
        ida                                                         as interview_id,

        --------------------------------------------------------------------------
        -- INTERVIEW DATE
        -- Raw format is YYYYMMDD as a string (e.g. "20230307")
        -- Empty strings become NULL via nullif before casting
        --------------------------------------------------------------------------
        case
            when nullif(intdate, '') is not null
                and length(trim(intdate)) = 8
            then strptime(trim(intdate), '%Y%m%d')::date
        end                                                         as interview_date,

        surv                                                        as survey_version,
        nullif(trim(zone), '')                                      as zone,

        --------------------------------------------------------------------------
        -- FIRM DEMOGRAPHICS (d-series)
        -- Raw codes kept as integers; labels added in intermediate layer
        --------------------------------------------------------------------------
        nullif(trim(d0), '')                                        as country_code,
        try_cast(nullif(trim(d1_rec), '') as integer)               as employee_band_code,
        try_cast(nullif(trim(d2), '') as integer)                   as enterprise_type_code,
        try_cast(nullif(trim(d3_rec), '') as integer)               as sector_code,
        try_cast(nullif(trim(d4), '') as integer)                   as turnover_code,
        try_cast(nullif(trim(d5_rec), '') as integer)               as firm_age_code,
        try_cast(nullif(trim(d6), '') as integer)                   as ownership_code,
        nullif(trim(d7), '')                                        as export_share_raw,
        try_cast(nullif(trim(d7_rec), '') as integer)               as export_share_code,

        --------------------------------------------------------------------------
        -- SURVEY WEIGHTS
        --------------------------------------------------------------------------
        try_cast(nullif(trim(wgtcommon), '') as double)             as weight_common,
        try_cast(nullif(trim(wgtentr), '') as double)               as weight_enterprise,
        try_cast(nullif(trim(wgtoldcommon), '') as double)          as weight_old_common,
        try_cast(nullif(trim(wgtoldentr), '') as double)            as weight_old_enterprise,

        --------------------------------------------------------------------------
        -- EXPERIMENT FLAGS (randomised question routing in some waves)
        --------------------------------------------------------------------------
        try_cast(nullif(trim(experiment_1), '') as integer)         as experiment_1,
        try_cast(nullif(trim(experiment_2), '') as integer)         as experiment_2,
        try_cast(nullif(trim(experiment_3), '') as integer)         as experiment_3,

        --------------------------------------------------------------------------
        -- ECB COMPOSITE INDICATORS
        -- Floats (e.g. 0.5, 0.25); NULL when firm not in scope for that index
        --------------------------------------------------------------------------
        try_cast(nullif(trim(ind_a), '') as double)                 as ind_a,
        try_cast(nullif(trim(ind_a_g1), '') as double)              as ind_a_grouped,
        try_cast(nullif(trim(ind_b), '') as double)                 as ind_b,
        try_cast(nullif(trim(ind_b_g1), '') as double)              as ind_b_grouped,
        try_cast(nullif(trim(ind_c), '') as double)                 as ind_c,
        try_cast(nullif(trim(ind_c_g1), '') as double)              as ind_c_grouped,
        try_cast(nullif(trim(ind_d), '') as double)                 as ind_d,
        try_cast(nullif(trim(ind_d_g1), '') as double)              as ind_d_grouped,
        try_cast(nullif(trim(ind_f), '') as double)                 as ind_f,
        try_cast(nullif(trim(ind_f_g1), '') as double)              as ind_f_grouped,
        try_cast(nullif(trim(ind_fgap), '') as double)              as ind_fgap,
        try_cast(nullif(trim(ind_fgap_g1), '') as double)           as ind_fgap_grouped,
        try_cast(nullif(trim(ind_fgap_broad), '') as double)        as ind_fgap_broad,
        try_cast(nullif(trim(ind_fgap_broad_g1), '') as double)     as ind_fgap_broad_grouped,
        try_cast(nullif(trim(ind_g), '') as double)                 as ind_g,
        try_cast(nullif(trim(ind_g_g1), '') as double)              as ind_g_grouped,
        try_cast(nullif(trim(ind_h), '') as double)                 as ind_h,
        try_cast(nullif(trim(ind_h_g1), '') as double)              as ind_h_grouped,

        --------------------------------------------------------------------------
        -- FIRM HEALTH FLAGS
        --------------------------------------------------------------------------
        try_cast(nullif(trim(profitable), '') as integer)           as profitable_6m,
        try_cast(nullif(trim(profitable_g1), '') as integer)        as profitable_3m,
        try_cast(nullif(trim(vulnerable), '') as integer)           as vulnerable_6m,
        try_cast(nullif(trim(vulnerable_g1), '') as integer)        as vulnerable_3m,

        --------------------------------------------------------------------------
        -- SECTION Q0 — SCREENER / ROUTING
        --------------------------------------------------------------------------
        try_cast(nullif(trim(q0), '') as integer)                   as q0,
        try_cast(nullif(trim(q0b_1), '') as integer)                as q0b_1,
        try_cast(nullif(trim(q0b_1_g1), '') as integer)             as q0b_1_3m,
        try_cast(nullif(trim(q0b_2), '') as integer)                as q0b_2,
        try_cast(nullif(trim(q0b_2_g1), '') as integer)             as q0b_2_3m,
        try_cast(nullif(trim(q0b_3), '') as integer)                as q0b_3,
        try_cast(nullif(trim(q0b_3_g1), '') as integer)             as q0b_3_3m,
        try_cast(nullif(trim(q0b_4), '') as integer)                as q0b_4,
        try_cast(nullif(trim(q0b_4_g1), '') as integer)             as q0b_4_3m,
        try_cast(nullif(trim(q0b_5), '') as integer)                as q0b_5,
        try_cast(nullif(trim(q0b_5_g1), '') as integer)             as q0b_5_3m,
        try_cast(nullif(trim(q0b_6), '') as integer)                as q0b_6,
        try_cast(nullif(trim(q0b_6_g1), '') as integer)             as q0b_6_3m,
        try_cast(nullif(trim(q0b_7), '') as integer)                as q0b_7,
        try_cast(nullif(trim(q0b_7_g1), '') as integer)             as q0b_7_3m,
        nullif(trim(q0b_7_open), '')                                as q0b_7_open,
        try_cast(nullif(trim(q0c), '') as integer)                  as q0c,

        --------------------------------------------------------------------------
        -- SECTION Q1 — BUSINESS SITUATION (turnover, costs, profits, employees)
        --------------------------------------------------------------------------
        try_cast(nullif(trim(q1_a), '') as integer)                 as q1_a,
        try_cast(nullif(trim(q1_b), '') as integer)                 as q1_b,
        try_cast(nullif(trim(q1_c), '') as integer)                 as q1_c,
        try_cast(nullif(trim(q1_d), '') as integer)                 as q1_d,

        --------------------------------------------------------------------------
        -- SECTION Q2 — FINANCING SOURCES USED
        --------------------------------------------------------------------------
        try_cast(nullif(trim(q2_a), '') as integer)                 as q2_a,
        try_cast(nullif(trim(q2_a_g1), '') as integer)              as q2_a_grouped,
        try_cast(nullif(trim(q2_b), '') as integer)                 as q2_b,
        try_cast(nullif(trim(q2_b_g1), '') as integer)              as q2_b_grouped,
        try_cast(nullif(trim(q2_c), '') as integer)                 as q2_c,
        try_cast(nullif(trim(q2_c_g1), '') as integer)              as q2_c_grouped,
        try_cast(nullif(trim(q2_d), '') as integer)                 as q2_d,
        try_cast(nullif(trim(q2_d_g1), '') as integer)              as q2_d_grouped,
        try_cast(nullif(trim(q2_e), '') as integer)                 as q2_e,
        try_cast(nullif(trim(q2_e_g1), '') as integer)              as q2_e_grouped,
        try_cast(nullif(trim(q2_f), '') as integer)                 as q2_f,
        try_cast(nullif(trim(q2_g), '') as integer)                 as q2_g,
        try_cast(nullif(trim(q2_g_g1), '') as integer)              as q2_g_grouped,
        try_cast(nullif(trim(q2_h), '') as integer)                 as q2_h,
        try_cast(nullif(trim(q2_h_g1), '') as integer)              as q2_h_grouped,
        try_cast(nullif(trim(q2_i), '') as integer)                 as q2_i,
        try_cast(nullif(trim(q2_i_g1), '') as integer)              as q2_i_grouped,
        try_cast(nullif(trim(q2_j), '') as integer)                 as q2_j,
        try_cast(nullif(trim(q2_j_g1), '') as integer)              as q2_j_grouped,
        try_cast(nullif(trim(q2_j_g1_rec), '') as integer)          as q2_j_grouped_rec,
        try_cast(nullif(trim(q2_j_rec), '') as integer)             as q2_j_rec,

        --------------------------------------------------------------------------
        -- SECTION Q3 — MOST PRESSING PROBLEM
        --------------------------------------------------------------------------
        try_cast(nullif(trim(q3), '') as integer)                   as q3,

        --------------------------------------------------------------------------
        -- SECTION Q4 — CHANGE IN AVAILABILITY OF FINANCING INSTRUMENTS
        --------------------------------------------------------------------------
        try_cast(nullif(trim(q4_a), '') as integer)                 as q4_a,
        try_cast(nullif(trim(q4_a_rec), '') as integer)             as q4_a_rec,
        try_cast(nullif(trim(q4_a_g1_rec), '') as integer)          as q4_a_grouped_rec,
        try_cast(nullif(trim(q4_b), '') as integer)                 as q4_b,
        try_cast(nullif(trim(q4_b_rec), '') as integer)             as q4_b_rec,
        try_cast(nullif(trim(q4_b_g1_rec), '') as integer)          as q4_b_grouped_rec,
        try_cast(nullif(trim(q4_c), '') as integer)                 as q4_c,
        try_cast(nullif(trim(q4_c_rec), '') as integer)             as q4_c_rec,
        try_cast(nullif(trim(q4_c_g1_rec), '') as integer)          as q4_c_grouped_rec,
        try_cast(nullif(trim(q4_d), '') as integer)                 as q4_d,
        try_cast(nullif(trim(q4_d_rec), '') as integer)             as q4_d_rec,
        try_cast(nullif(trim(q4_d_g1_rec), '') as integer)          as q4_d_grouped_rec,
        try_cast(nullif(trim(q4_e), '') as integer)                 as q4_e,
        try_cast(nullif(trim(q4_e_rec), '') as integer)             as q4_e_rec,
        try_cast(nullif(trim(q4_e_g1_rec), '') as integer)          as q4_e_grouped_rec,
        try_cast(nullif(trim(q4_f), '') as integer)                 as q4_f,
        try_cast(nullif(trim(q4_f_rec), '') as integer)             as q4_f_rec,
        try_cast(nullif(trim(q4_f_g1_rec), '') as integer)          as q4_f_grouped_rec,
        try_cast(nullif(trim(q4_g), '') as integer)                 as q4_g,
        try_cast(nullif(trim(q4_g_rec), '') as integer)             as q4_g_rec,
        try_cast(nullif(trim(q4_g_g1_rec), '') as integer)          as q4_g_grouped_rec,
        try_cast(nullif(trim(q4_h), '') as integer)                 as q4_h,
        try_cast(nullif(trim(q4_h_rec), '') as integer)             as q4_h_rec,
        try_cast(nullif(trim(q4_h_g1_rec), '') as integer)          as q4_h_grouped_rec,
        try_cast(nullif(trim(q4_i), '') as integer)                 as q4_i,
        try_cast(nullif(trim(q4_j), '') as integer)                 as q4_j,
        try_cast(nullif(trim(q4_j_rec), '') as integer)             as q4_j_rec,
        try_cast(nullif(trim(q4_j_g1_rec), '') as integer)          as q4_j_grouped_rec,
        try_cast(nullif(trim(q4_k), '') as integer)                 as q4_k,
        try_cast(nullif(trim(q4_l), '') as integer)                 as q4_l,
        try_cast(nullif(trim(q4_m), '') as integer)                 as q4_m,
        try_cast(nullif(trim(q4_m_rec), '') as integer)             as q4_m_rec,
        try_cast(nullif(trim(q4_m_g1_rec), '') as integer)          as q4_m_grouped_rec,
        try_cast(nullif(trim(q4_p), '') as integer)                 as q4_p,
        try_cast(nullif(trim(q4_p_rec), '') as integer)             as q4_p_rec,
        try_cast(nullif(trim(q4_p_g1_rec), '') as integer)          as q4_p_grouped_rec,
        try_cast(nullif(trim(q4_r), '') as integer)                 as q4_r,
        try_cast(nullif(trim(q4_r_rec), '') as integer)             as q4_r_rec,
        try_cast(nullif(trim(q4_r_g1_rec), '') as integer)          as q4_r_grouped_rec,

        --------------------------------------------------------------------------
        -- SECTION Q4A — REASONS FOR CHANGE IN AVAILABILITY
        --------------------------------------------------------------------------
        try_cast(nullif(trim(q4a_a), '') as integer)                as q4a_a,
        try_cast(nullif(trim(q4a_a_g1), '') as integer)             as q4a_a_grouped,
        try_cast(nullif(trim(q4a_b), '') as integer)                as q4a_b,
        try_cast(nullif(trim(q4a_b_g1), '') as integer)             as q4a_b_grouped,
        try_cast(nullif(trim(q4a_c), '') as integer)                as q4a_c,
        try_cast(nullif(trim(q4a_c_g1), '') as integer)             as q4a_c_grouped,
        try_cast(nullif(trim(q4a_d), '') as integer)                as q4a_d,
        try_cast(nullif(trim(q4a_d_g1), '') as integer)             as q4a_d_grouped,
        try_cast(nullif(trim(q4a_e), '') as integer)                as q4a_e,
        try_cast(nullif(trim(q4a_e_g1), '') as integer)             as q4a_e_grouped,
        try_cast(nullif(trim(q4a_f), '') as integer)                as q4a_f,
        try_cast(nullif(trim(q4a_f_g1), '') as integer)             as q4a_f_grouped,
        try_cast(nullif(trim(q4a_h), '') as integer)                as q4a_h,
        try_cast(nullif(trim(q4a_h_g1), '') as integer)             as q4a_h_grouped,
        try_cast(nullif(trim(q4a_j), '') as integer)                as q4a_j,
        try_cast(nullif(trim(q4a_j_g1), '') as integer)             as q4a_j_grouped,
        try_cast(nullif(trim(q4a_m), '') as integer)                as q4a_m,
        try_cast(nullif(trim(q4a_m_g1), '') as integer)             as q4a_m_grouped,
        try_cast(nullif(trim(q4a_p), '') as integer)                as q4a_p,
        try_cast(nullif(trim(q4a_p_g1), '') as integer)             as q4a_p_grouped,
        try_cast(nullif(trim(q4a_r), '') as integer)                as q4a_r,
        try_cast(nullif(trim(q4a_r_g1), '') as integer)             as q4a_r_grouped,

        --------------------------------------------------------------------------
        -- SECTION Q5 — CHANGE IN NEED FOR FINANCING
        --------------------------------------------------------------------------
        try_cast(nullif(trim(q5_a), '') as integer)                 as q5_a,
        try_cast(nullif(trim(q5_a_rec), '') as integer)             as q5_a_rec,
        try_cast(nullif(trim(q5_a_g1), '') as integer)              as q5_a_grouped,
        try_cast(nullif(trim(q5_a_g1_rec), '') as integer)          as q5_a_grouped_rec,
        try_cast(nullif(trim(q5_b), '') as integer)                 as q5_b,
        try_cast(nullif(trim(q5_b_rec), '') as integer)             as q5_b_rec,
        try_cast(nullif(trim(q5_b_g1), '') as integer)              as q5_b_grouped,
        try_cast(nullif(trim(q5_b_g1_rec), '') as integer)          as q5_b_grouped_rec,
        try_cast(nullif(trim(q5_c), '') as integer)                 as q5_c,
        try_cast(nullif(trim(q5_c_rec), '') as integer)             as q5_c_rec,
        try_cast(nullif(trim(q5_c_g1), '') as integer)              as q5_c_grouped,
        try_cast(nullif(trim(q5_c_g1_rec), '') as integer)          as q5_c_grouped_rec,
        try_cast(nullif(trim(q5_d), '') as integer)                 as q5_d,
        try_cast(nullif(trim(q5_d_rec), '') as integer)             as q5_d_rec,
        try_cast(nullif(trim(q5_d_g1), '') as integer)              as q5_d_grouped,
        try_cast(nullif(trim(q5_d_g1_rec), '') as integer)          as q5_d_grouped_rec,
        try_cast(nullif(trim(q5_e), '') as integer)                 as q5_e,
        try_cast(nullif(trim(q5_e_rec), '') as integer)             as q5_e_rec,
        try_cast(nullif(trim(q5_f), '') as integer)                 as q5_f,
        try_cast(nullif(trim(q5_f_rec), '') as integer)             as q5_f_rec,
        try_cast(nullif(trim(q5_f_g1), '') as integer)              as q5_f_grouped,
        try_cast(nullif(trim(q5_f_g1_rec), '') as integer)          as q5_f_grouped_rec,
        try_cast(nullif(trim(q5_g), '') as integer)                 as q5_g,
        try_cast(nullif(trim(q5_g_rec), '') as integer)             as q5_g_rec,
        try_cast(nullif(trim(q5_g_g1), '') as integer)              as q5_g_grouped,
        try_cast(nullif(trim(q5_g_g1_rec), '') as integer)          as q5_g_grouped_rec,
        try_cast(nullif(trim(q5_h), '') as integer)                 as q5_h,
        try_cast(nullif(trim(q5_h_rec), '') as integer)             as q5_h_rec,
        try_cast(nullif(trim(q5_h_g1), '') as integer)              as q5_h_grouped,
        try_cast(nullif(trim(q5_h_g1_rec), '') as integer)          as q5_h_grouped_rec,

        --------------------------------------------------------------------------
        -- SECTION Q6 — BANK RELATIONSHIP
        --------------------------------------------------------------------------
        try_cast(nullif(trim(q6_a), '') as integer)                 as q6_a,
        try_cast(nullif(trim(q6_b), '') as integer)                 as q6_b,
        try_cast(nullif(trim(q6_c), '') as integer)                 as q6_c,
        try_cast(nullif(trim(q6_d), '') as integer)                 as q6_d,
        try_cast(nullif(trim(q6a_1), '') as integer)                as q6a_1,
        try_cast(nullif(trim(q6a_1_g1), '') as integer)             as q6a_1_grouped,
        try_cast(nullif(trim(q6a_2), '') as integer)                as q6a_2,
        try_cast(nullif(trim(q6a_2_g1), '') as integer)             as q6a_2_grouped,
        try_cast(nullif(trim(q6a_3), '') as integer)                as q6a_3,
        try_cast(nullif(trim(q6a_3_g1), '') as integer)             as q6a_3_grouped,
        try_cast(nullif(trim(q6a_4), '') as integer)                as q6a_4,
        try_cast(nullif(trim(q6a_4_g1), '') as integer)             as q6a_4_grouped,
        try_cast(nullif(trim(q6a_5), '') as integer)                as q6a_5,
        try_cast(nullif(trim(q6a_5_g1), '') as integer)             as q6a_5_grouped,
        try_cast(nullif(trim(q6a_6), '') as integer)                as q6a_6,
        try_cast(nullif(trim(q6a_6_g1), '') as integer)             as q6a_6_grouped,

        --------------------------------------------------------------------------
        -- SECTION Q7A/Q7B — OBSTACLES TO OBTAINING FINANCE
        --------------------------------------------------------------------------
        try_cast(nullif(trim(q7a_a), '') as integer)                as q7a_a,
        try_cast(nullif(trim(q7a_a_rec), '') as integer)            as q7a_a_rec,
        try_cast(nullif(trim(q7a_a_g1), '') as integer)             as q7a_a_grouped,
        try_cast(nullif(trim(q7a_a_g1_rec), '') as integer)         as q7a_a_grouped_rec,
        try_cast(nullif(trim(q7a_b), '') as integer)                as q7a_b,
        try_cast(nullif(trim(q7a_b_rec), '') as integer)            as q7a_b_rec,
        try_cast(nullif(trim(q7a_b_g1), '') as integer)             as q7a_b_grouped,
        try_cast(nullif(trim(q7a_b_g1_rec), '') as integer)         as q7a_b_grouped_rec,
        try_cast(nullif(trim(q7a_c), '') as integer)                as q7a_c,
        try_cast(nullif(trim(q7a_c_rec), '') as integer)            as q7a_c_rec,
        try_cast(nullif(trim(q7a_c_g1), '') as integer)             as q7a_c_grouped,
        try_cast(nullif(trim(q7a_c_g1_rec), '') as integer)         as q7a_c_grouped_rec,
        try_cast(nullif(trim(q7a_d), '') as integer)                as q7a_d,
        try_cast(nullif(trim(q7a_d_rec), '') as integer)            as q7a_d_rec,
        try_cast(nullif(trim(q7a_d_g1), '') as integer)             as q7a_d_grouped,
        try_cast(nullif(trim(q7a_d_g1_rec), '') as integer)         as q7a_d_grouped_rec,
        try_cast(nullif(trim(q7b_a), '') as integer)                as q7b_a,
        try_cast(nullif(trim(q7b_a_rec), '') as integer)            as q7b_a_rec,
        try_cast(nullif(trim(q7b_a_g1), '') as integer)             as q7b_a_grouped,
        try_cast(nullif(trim(q7b_a_g1_rec), '') as integer)         as q7b_a_grouped_rec,
        try_cast(nullif(trim(q7b_b), '') as integer)                as q7b_b,
        try_cast(nullif(trim(q7b_b_rec), '') as integer)            as q7b_b_rec,
        try_cast(nullif(trim(q7b_b_g1), '') as integer)             as q7b_b_grouped,
        try_cast(nullif(trim(q7b_b_g1_rec), '') as integer)         as q7b_b_grouped_rec,
        try_cast(nullif(trim(q7b_c), '') as integer)                as q7b_c,
        try_cast(nullif(trim(q7b_c_rec), '') as integer)            as q7b_c_rec,
        try_cast(nullif(trim(q7b_c_g1), '') as integer)             as q7b_c_grouped,
        try_cast(nullif(trim(q7b_c_g1_rec), '') as integer)         as q7b_c_grouped_rec,
        try_cast(nullif(trim(q7b_d), '') as integer)                as q7b_d,
        try_cast(nullif(trim(q7b_d_rec), '') as integer)            as q7b_d_rec,
        try_cast(nullif(trim(q7b_d_g1), '') as integer)             as q7b_d_grouped,
        try_cast(nullif(trim(q7b_d_g1_rec), '') as integer)         as q7b_d_grouped_rec,

        --------------------------------------------------------------------------
        -- SECTION Q8 — BANK LOAN DETAILS (amount, interest rate)
        -- Note: q8b and its sub-fields may contain -99 (refused) in addition
        -- to the standard -1/-2 non-response codes
        --------------------------------------------------------------------------
        try_cast(nullif(trim(q8a), '') as integer)                  as q8a,
        try_cast(nullif(trim(q8a_rec), '') as integer)              as q8a_rec,
        try_cast(nullif(trim(q8b), '') as double)                   as q8b,
        try_cast(nullif(trim(q8b_type), '') as integer)             as q8b_type,
        try_cast(nullif(trim(q8b_fix), '') as double)               as q8b_fix,
        try_cast(nullif(trim(q8b_var_referencerate), '') as double) as q8b_var_referencerate,
        try_cast(nullif(trim(q8b_var_spread), '') as double)        as q8b_var_spread,
        try_cast(nullif(trim(q8b_var_total), '') as double)         as q8b_var_total,

        --------------------------------------------------------------------------
        -- SECTION Q9 — APPLICATION OUTCOMES BY INSTRUMENT
        --------------------------------------------------------------------------
        try_cast(nullif(trim(q9_a), '') as integer)                 as q9_a,
        try_cast(nullif(trim(q9_a_rec), '') as integer)             as q9_a_rec,
        try_cast(nullif(trim(q9_a_g1), '') as integer)              as q9_a_grouped,
        try_cast(nullif(trim(q9_a_g1_rec), '') as integer)          as q9_a_grouped_rec,
        try_cast(nullif(trim(q9_b), '') as integer)                 as q9_b,
        try_cast(nullif(trim(q9_b_rec), '') as integer)             as q9_b_rec,
        try_cast(nullif(trim(q9_b_g1), '') as integer)              as q9_b_grouped,
        try_cast(nullif(trim(q9_b_g1_rec), '') as integer)          as q9_b_grouped_rec,
        try_cast(nullif(trim(q9_c), '') as integer)                 as q9_c,
        try_cast(nullif(trim(q9_c_rec), '') as integer)             as q9_c_rec,
        try_cast(nullif(trim(q9_c_g1), '') as integer)              as q9_c_grouped,
        try_cast(nullif(trim(q9_c_g1_rec), '') as integer)          as q9_c_grouped_rec,
        try_cast(nullif(trim(q9_d), '') as integer)                 as q9_d,
        try_cast(nullif(trim(q9_d_rec), '') as integer)             as q9_d_rec,
        try_cast(nullif(trim(q9_d_g1), '') as integer)              as q9_d_grouped,
        try_cast(nullif(trim(q9_d_g1_rec), '') as integer)          as q9_d_grouped_rec,
        try_cast(nullif(trim(q9_e), '') as integer)                 as q9_e,
        try_cast(nullif(trim(q9_e_rec), '') as integer)             as q9_e_rec,
        try_cast(nullif(trim(q9_f), '') as integer)                 as q9_f,
        try_cast(nullif(trim(q9_f_rec), '') as integer)             as q9_f_rec,
        try_cast(nullif(trim(q9_f_g1), '') as integer)              as q9_f_grouped,
        try_cast(nullif(trim(q9_f_g1_rec), '') as integer)          as q9_f_grouped_rec,
        try_cast(nullif(trim(q9_g), '') as integer)                 as q9_g,
        try_cast(nullif(trim(q9_g_rec), '') as integer)             as q9_g_rec,
        try_cast(nullif(trim(q9_g_g1), '') as integer)              as q9_g_grouped,
        try_cast(nullif(trim(q9_g_g1_rec), '') as integer)          as q9_g_grouped_rec,
        try_cast(nullif(trim(q9_h), '') as integer)                 as q9_h,
        try_cast(nullif(trim(q9_h_rec), '') as integer)             as q9_h_rec,
        try_cast(nullif(trim(q9_h_g1), '') as integer)              as q9_h_grouped,
        try_cast(nullif(trim(q9_h_g1_rec), '') as integer)          as q9_h_grouped_rec,

        --------------------------------------------------------------------------
        -- SECTION Q10 — TERMS AND CONDITIONS OF FINANCING
        --------------------------------------------------------------------------
        try_cast(nullif(trim(q10_a), '') as integer)                as q10_a,
        try_cast(nullif(trim(q10_a_rec), '') as integer)            as q10_a_rec,
        try_cast(nullif(trim(q10_a_g1), '') as integer)             as q10_a_grouped,
        try_cast(nullif(trim(q10_a_g1_rec), '') as integer)         as q10_a_grouped_rec,
        try_cast(nullif(trim(q10_b), '') as integer)                as q10_b,
        try_cast(nullif(trim(q10_b_rec), '') as integer)            as q10_b_rec,
        try_cast(nullif(trim(q10_b_g1), '') as integer)             as q10_b_grouped,
        try_cast(nullif(trim(q10_b_g1_rec), '') as integer)         as q10_b_grouped_rec,
        try_cast(nullif(trim(q10_c), '') as integer)                as q10_c,
        try_cast(nullif(trim(q10_c_rec), '') as integer)            as q10_c_rec,
        try_cast(nullif(trim(q10_c_g1), '') as integer)             as q10_c_grouped,
        try_cast(nullif(trim(q10_c_g1_rec), '') as integer)         as q10_c_grouped_rec,
        try_cast(nullif(trim(q10_d), '') as integer)                as q10_d,
        try_cast(nullif(trim(q10_d_rec), '') as integer)            as q10_d_rec,
        try_cast(nullif(trim(q10_d_g1), '') as integer)             as q10_d_grouped,
        try_cast(nullif(trim(q10_d_g1_rec), '') as integer)         as q10_d_grouped_rec,
        try_cast(nullif(trim(q10_e), '') as integer)                as q10_e,
        try_cast(nullif(trim(q10_e_rec), '') as integer)            as q10_e_rec,
        try_cast(nullif(trim(q10_e_g1), '') as integer)             as q10_e_grouped,
        try_cast(nullif(trim(q10_e_g1_rec), '') as integer)         as q10_e_grouped_rec,
        try_cast(nullif(trim(q10_f), '') as integer)                as q10_f,
        try_cast(nullif(trim(q10_f_rec), '') as integer)            as q10_f_rec,
        try_cast(nullif(trim(q10_f_g1), '') as integer)             as q10_f_grouped,
        try_cast(nullif(trim(q10_f_g1_rec), '') as integer)         as q10_f_grouped_rec,

        --------------------------------------------------------------------------
        -- SECTION Q11 — MOST IMPORTANT OBSTACLE TO BUSINESS
        --------------------------------------------------------------------------
        try_cast(nullif(trim(q11_a), '') as integer)                as q11_a,
        try_cast(nullif(trim(q11_a_g1), '') as integer)             as q11_a_grouped,
        try_cast(nullif(trim(q11_b), '') as integer)                as q11_b,
        try_cast(nullif(trim(q11_b_g1), '') as integer)             as q11_b_grouped,
        try_cast(nullif(trim(q11_c), '') as integer)                as q11_c,
        try_cast(nullif(trim(q11_c_g1), '') as integer)             as q11_c_grouped,
        try_cast(nullif(trim(q11_d), '') as integer)                as q11_d,
        try_cast(nullif(trim(q11_d_g1), '') as integer)             as q11_d_grouped,
        try_cast(nullif(trim(q11_e), '') as integer)                as q11_e,
        try_cast(nullif(trim(q11_e_g1), '') as integer)             as q11_e_grouped,
        try_cast(nullif(trim(q11_f), '') as integer)                as q11_f,
        try_cast(nullif(trim(q11_f_rec), '') as integer)            as q11_f_rec,
        try_cast(nullif(trim(q11_f_g1), '') as integer)             as q11_f_grouped,
        try_cast(nullif(trim(q11_f_g1_rec), '') as integer)         as q11_f_grouped_rec,
        try_cast(nullif(trim(q11_g), '') as integer)                as q11_g,
        try_cast(nullif(trim(q11_g_rec), '') as integer)            as q11_g_rec,
        try_cast(nullif(trim(q11_g_g1), '') as integer)             as q11_g_grouped,
        try_cast(nullif(trim(q11_g_g1_rec), '') as integer)         as q11_g_grouped_rec,
        try_cast(nullif(trim(q11_h), '') as integer)                as q11_h,
        try_cast(nullif(trim(q11_h_rec), '') as integer)            as q11_h_rec,
        try_cast(nullif(trim(q11_h_g1), '') as integer)             as q11_h_grouped,
        try_cast(nullif(trim(q11_h_g1_rec), '') as integer)         as q11_h_grouped_rec,
        try_cast(nullif(trim(q11_i), '') as integer)                as q11_i,
        try_cast(nullif(trim(q11_i_g1), '') as integer)             as q11_i_grouped,

        --------------------------------------------------------------------------
        -- SECTIONS Q12–Q17 — FUTURE NEEDS, INNOVATION, TRADE CREDIT
        --------------------------------------------------------------------------
        try_cast(nullif(trim(q12), '') as integer)                  as q12,
        try_cast(nullif(trim(q13), '') as integer)                  as q13,
        try_cast(nullif(trim(q14_a), '') as integer)                as q14_a,
        try_cast(nullif(trim(q14_b), '') as integer)                as q14_b,
        try_cast(nullif(trim(q14_c), '') as integer)                as q14_c,
        try_cast(nullif(trim(q14_d), '') as integer)                as q14_d,
        try_cast(nullif(trim(q14_e), '') as integer)                as q14_e,
        try_cast(nullif(trim(q14_f), '') as integer)                as q14_f,
        try_cast(nullif(trim(q14_g), '') as integer)                as q14_g,
        try_cast(nullif(trim(q14_h), '') as integer)                as q14_h,
        try_cast(nullif(trim(q16_a), '') as integer)                as q16_a,
        try_cast(nullif(trim(q16_b), '') as integer)                as q16_b,
        try_cast(nullif(trim(q17), '') as integer)                  as q17,

        --------------------------------------------------------------------------
        -- SECTIONS Q19–Q26 — GOVERNMENT SUPPORT, FIRM EXPECTATIONS, OTHER
        --------------------------------------------------------------------------
        try_cast(nullif(trim(q19_a), '') as integer)                as q19_a,
        try_cast(nullif(trim(q19_b), '') as integer)                as q19_b,
        try_cast(nullif(trim(q20), '') as integer)                  as q20,
        try_cast(nullif(trim(q21), '') as integer)                  as q21,
        try_cast(nullif(trim(q22), '') as integer)                  as q22,
        try_cast(nullif(trim(q22_a), '') as integer)                as q22_a,
        try_cast(nullif(trim(q22_b), '') as integer)                as q22_b,
        try_cast(nullif(trim(q22_rec), '') as integer)              as q22_rec,
        try_cast(nullif(trim(q23_a), '') as integer)                as q23_a,
        try_cast(nullif(trim(q23_a_rec), '') as integer)            as q23_a_rec,
        try_cast(nullif(trim(q23_a_g1), '') as integer)             as q23_a_grouped,
        try_cast(nullif(trim(q23_a_g1_rec), '') as integer)         as q23_a_grouped_rec,
        try_cast(nullif(trim(q23_b), '') as integer)                as q23_b,
        try_cast(nullif(trim(q23_b_rec), '') as integer)            as q23_b_rec,
        try_cast(nullif(trim(q23_b_g1), '') as integer)             as q23_b_grouped,
        try_cast(nullif(trim(q23_b_g1_rec), '') as integer)         as q23_b_grouped_rec,
        try_cast(nullif(trim(q23_c), '') as integer)                as q23_c,
        try_cast(nullif(trim(q23_c_rec), '') as integer)            as q23_c_rec,
        try_cast(nullif(trim(q23_c_g1), '') as integer)             as q23_c_grouped,
        try_cast(nullif(trim(q23_c_g1_rec), '') as integer)         as q23_c_grouped_rec,
        try_cast(nullif(trim(q23_d), '') as integer)                as q23_d,
        try_cast(nullif(trim(q23_d_rec), '') as integer)            as q23_d_rec,
        try_cast(nullif(trim(q23_d_g1), '') as integer)             as q23_d_grouped,
        try_cast(nullif(trim(q23_d_g1_rec), '') as integer)         as q23_d_grouped_rec,
        try_cast(nullif(trim(q23_e), '') as integer)                as q23_e,
        try_cast(nullif(trim(q23_e_rec), '') as integer)            as q23_e_rec,
        try_cast(nullif(trim(q23_e_g1), '') as integer)             as q23_e_grouped,
        try_cast(nullif(trim(q23_e_g1_rec), '') as integer)         as q23_e_grouped_rec,
        try_cast(nullif(trim(q23_f), '') as integer)                as q23_f,
        try_cast(nullif(trim(q23_f_rec), '') as integer)            as q23_f_rec,
        try_cast(nullif(trim(q23_g), '') as integer)                as q23_g,
        try_cast(nullif(trim(q23_g_rec), '') as integer)            as q23_g_rec,
        try_cast(nullif(trim(q23_g_g1), '') as integer)             as q23_g_grouped,
        try_cast(nullif(trim(q23_g_g1_rec), '') as integer)         as q23_g_grouped_rec,
        try_cast(nullif(trim(q23_i), '') as integer)                as q23_i,
        try_cast(nullif(trim(q23_i_rec), '') as integer)            as q23_i_rec,
        try_cast(nullif(trim(q23_i_g1), '') as integer)             as q23_i_grouped,
        try_cast(nullif(trim(q23_i_g1_rec), '') as integer)         as q23_i_grouped_rec,
        try_cast(nullif(trim(q23_j), '') as integer)                as q23_j,
        try_cast(nullif(trim(q23_j_rec), '') as integer)            as q23_j_rec,
        try_cast(nullif(trim(q23_j_g1), '') as integer)             as q23_j_grouped,
        try_cast(nullif(trim(q23_j_g1_rec), '') as integer)         as q23_j_grouped_rec,
        try_cast(nullif(trim(q24), '') as integer)                  as q24,
        try_cast(nullif(trim(q24_a), '') as integer)                as q24_a,
        try_cast(nullif(trim(q24_b), '') as integer)                as q24_b,
        try_cast(nullif(trim(q24_c), '') as integer)                as q24_c,
        try_cast(nullif(trim(q24_d), '') as integer)                as q24_d,
        try_cast(nullif(trim(q24_e), '') as integer)                as q24_e,
        try_cast(nullif(trim(q24_f), '') as integer)                as q24_f,
        try_cast(nullif(trim(q25), '') as integer)                  as q25,
        try_cast(nullif(trim(q26), '') as integer)                  as q26,
        try_cast(nullif(trim(q26_a), '') as integer)                as q26_a,
        try_cast(nullif(trim(q26_a_g1), '') as integer)             as q26_a_grouped,
        try_cast(nullif(trim(q26_b), '') as integer)                as q26_b,
        try_cast(nullif(trim(q26_b_g1), '') as integer)             as q26_b_grouped,

        --------------------------------------------------------------------------
        -- SECTIONS Q31–Q34 — SUPPLEMENTARY / COUNTRY-SPECIFIC
        --------------------------------------------------------------------------
        try_cast(nullif(trim(q31_a), '') as integer)                as q31_a,
        try_cast(nullif(trim(q31_b), '') as integer)                as q31_b,
        try_cast(nullif(trim(q31_c), '') as integer)                as q31_c,
        try_cast(nullif(trim(q32), '') as integer)                  as q32,
        try_cast(nullif(trim(q33), '') as integer)                  as q33,
        try_cast(nullif(trim(q34_a), '') as integer)                as q34_a,
        try_cast(nullif(trim(q34_a_1), '') as integer)              as q34_a_1,
        try_cast(nullif(trim(q34_a_rec), '') as integer)            as q34_a_rec,
        try_cast(nullif(trim(q34_b), '') as integer)                as q34_b,
        try_cast(nullif(trim(q34_b_1), '') as integer)              as q34_b_1,
        try_cast(nullif(trim(q34_b_rec), '') as integer)            as q34_b_rec,
        try_cast(nullif(trim(q34_c), '') as integer)                as q34_c,
        try_cast(nullif(trim(q34_c_1), '') as integer)              as q34_c_1,
        try_cast(nullif(trim(q34_c_rec), '') as integer)            as q34_c_rec,
        try_cast(nullif(trim(q34_d), '') as integer)                as q34_d,
        try_cast(nullif(trim(q34_d_1), '') as integer)              as q34_d_1,
        try_cast(nullif(trim(q34_d_rec), '') as integer)            as q34_d_rec,

        --------------------------------------------------------------------------
        -- AD-HOC WAVE MODULES (qa* / qb*)
        -- These columns are wave-stamped and sparse by design.
        -- They are kept as-is (cast to integer) for the intermediate layer
        -- to unpivot into long format.
        --------------------------------------------------------------------------

        -- qa1 series
        try_cast(nullif(trim(qa1_2015h2), '') as integer)           as qa1_2015h2,
        try_cast(nullif(trim(qa1_2016h2), '') as integer)           as qa1_2016h2,
        try_cast(nullif(trim(qa1_2017h2), '') as integer)           as qa1_2017h2,
        try_cast(nullif(trim(qa1_2018h2), '') as integer)           as qa1_2018h2,
        try_cast(nullif(trim(qa1_2021h2), '') as integer)           as qa1_2021h2,
        try_cast(nullif(trim(qa1_1_2022h2), '') as integer)         as qa1_1_2022h2,
        try_cast(nullif(trim(qa1_2_2022h2), '') as integer)         as qa1_2_2022h2,
        try_cast(nullif(trim(qa1_c1_2022h2), '') as integer)        as qa1_c1_2022h2,
        try_cast(nullif(trim(qa1_2024q2), '') as integer)           as qa1_2024q2,
        try_cast(nullif(trim(qa1_2024q4), '') as integer)           as qa1_2024q4,
        try_cast(nullif(trim(qa1_2025q2), '') as integer)           as qa1_2025q2,
        try_cast(nullif(trim(qa1_2025q4), '') as integer)           as qa1_2025q4,
        try_cast(nullif(trim(qa1_a_2019h2), '') as integer)         as qa1_a_2019h2,
        try_cast(nullif(trim(qa1_b_2019h2), '') as integer)         as qa1_b_2019h2,
        try_cast(nullif(trim(qa1_c_2019h2), '') as integer)         as qa1_c_2019h2,
        try_cast(nullif(trim(qa1_d_2019h2), '') as integer)         as qa1_d_2019h2,
        try_cast(nullif(trim(qa1_e_2019h2), '') as integer)         as qa1_e_2019h2,
        try_cast(nullif(trim(qa1_f_2019h2), '') as integer)         as qa1_f_2019h2,
        try_cast(nullif(trim(qa1_g_2019h2), '') as integer)         as qa1_g_2019h2,
        try_cast(nullif(trim(qa1_a_2020h2), '') as integer)         as qa1_a_2020h2,
        try_cast(nullif(trim(qa1_b_2020h2), '') as integer)         as qa1_b_2020h2,
        try_cast(nullif(trim(qa1_c_2020h2), '') as integer)         as qa1_c_2020h2,

        -- qa1a series
        try_cast(nullif(trim(qa1a_1_2019h1), '') as integer)        as qa1a_1_2019h1,
        try_cast(nullif(trim(qa1a_2_2019h1), '') as integer)        as qa1a_2_2019h1,
        try_cast(nullif(trim(qa1a_3_2019h1), '') as integer)        as qa1a_3_2019h1,
        try_cast(nullif(trim(qa1a_1_2020h1), '') as integer)        as qa1a_1_2020h1,
        try_cast(nullif(trim(qa1a_2_2020h1), '') as integer)        as qa1a_2_2020h1,
        try_cast(nullif(trim(qa1a_3_2020h1), '') as integer)        as qa1a_3_2020h1,
        try_cast(nullif(trim(qa1a_10_2020h1), '') as integer)       as qa1a_10_2020h1,
        try_cast(nullif(trim(qa1a_1_2021h1), '') as integer)        as qa1a_1_2021h1,
        try_cast(nullif(trim(qa1a_2_2021h1), '') as integer)        as qa1a_2_2021h1,
        try_cast(nullif(trim(qa1a_3_2021h1), '') as integer)        as qa1a_3_2021h1,
        try_cast(nullif(trim(qa1a_10_2021h1), '') as integer)       as qa1a_10_2021h1,
        try_cast(nullif(trim(qa1a_1_2022h1), '') as integer)        as qa1a_1_2022h1,
        try_cast(nullif(trim(qa1a_2_2022h1), '') as integer)        as qa1a_2_2022h1,
        try_cast(nullif(trim(qa1a_3_2022h1), '') as integer)        as qa1a_3_2022h1,
        try_cast(nullif(trim(qa1a_10_2022h1), '') as integer)       as qa1a_10_2022h1,
        try_cast(nullif(trim(qa1a_1_2023h1), '') as integer)        as qa1a_1_2023h1,
        try_cast(nullif(trim(qa1a_2_2023h1), '') as integer)        as qa1a_2_2023h1,
        try_cast(nullif(trim(qa1a_3_2023h1), '') as integer)        as qa1a_3_2023h1,
        try_cast(nullif(trim(qa1a_10_2023h1), '') as integer)       as qa1a_10_2023h1,
        try_cast(nullif(trim(qa1a_1_2024q3), '') as integer)        as qa1a_1_2024q3,
        try_cast(nullif(trim(qa1a_2_2024q3), '') as integer)        as qa1a_2_2024q3,
        try_cast(nullif(trim(qa1a_3_2024q3), '') as integer)        as qa1a_3_2024q3,
        try_cast(nullif(trim(qa1a_10_2024q3), '') as integer)       as qa1a_10_2024q3,

        -- qa1b / qa1c series
        try_cast(nullif(trim(qa1b_2019h1), '') as integer)          as qa1b_2019h1,
        try_cast(nullif(trim(qa1b_2020h1), '') as integer)          as qa1b_2020h1,
        try_cast(nullif(trim(qa1b_2021h1), '') as integer)          as qa1b_2021h1,
        try_cast(nullif(trim(qa1b_2022h1), '') as integer)          as qa1b_2022h1,
        try_cast(nullif(trim(qa1b_2023h1), '') as integer)          as qa1b_2023h1,
        try_cast(nullif(trim(qa1b_2024q3), '') as integer)          as qa1b_2024q3,
        try_cast(nullif(trim(qa1c_4_2019h1), '') as integer)        as qa1c_4_2019h1,
        try_cast(nullif(trim(qa1c_5_2019h1), '') as integer)        as qa1c_5_2019h1,
        try_cast(nullif(trim(qa1c_6_2019h1), '') as integer)        as qa1c_6_2019h1,
        try_cast(nullif(trim(qa1c_7_2019h1), '') as integer)        as qa1c_7_2019h1,
        try_cast(nullif(trim(qa1c_8_2019h1), '') as integer)        as qa1c_8_2019h1,
        try_cast(nullif(trim(qa1c_9_2019h1), '') as integer)        as qa1c_9_2019h1,
        try_cast(nullif(trim(qa1c_4_2020h1), '') as integer)        as qa1c_4_2020h1,
        try_cast(nullif(trim(qa1c_5_2020h1), '') as integer)        as qa1c_5_2020h1,
        try_cast(nullif(trim(qa1c_6_2020h1), '') as integer)        as qa1c_6_2020h1,
        try_cast(nullif(trim(qa1c_7_2020h1), '') as integer)        as qa1c_7_2020h1,
        try_cast(nullif(trim(qa1c_8_2020h1), '') as integer)        as qa1c_8_2020h1,
        try_cast(nullif(trim(qa1c_9_2020h1), '') as integer)        as qa1c_9_2020h1,
        try_cast(nullif(trim(qa1c_4_2021h1), '') as integer)        as qa1c_4_2021h1,
        try_cast(nullif(trim(qa1c_5_2021h1), '') as integer)        as qa1c_5_2021h1,
        try_cast(nullif(trim(qa1c_6_2021h1), '') as integer)        as qa1c_6_2021h1,
        try_cast(nullif(trim(qa1c_7_2021h1), '') as integer)        as qa1c_7_2021h1,
        try_cast(nullif(trim(qa1c_8_2021h1), '') as integer)        as qa1c_8_2021h1,
        try_cast(nullif(trim(qa1c_9_2021h1), '') as integer)        as qa1c_9_2021h1,
        try_cast(nullif(trim(qa1c_4_2022h1), '') as integer)        as qa1c_4_2022h1,
        try_cast(nullif(trim(qa1c_5_2022h1), '') as integer)        as qa1c_5_2022h1,
        try_cast(nullif(trim(qa1c_6_2022h1), '') as integer)        as qa1c_6_2022h1,
        try_cast(nullif(trim(qa1c_7_2022h1), '') as integer)        as qa1c_7_2022h1,
        try_cast(nullif(trim(qa1c_8_2022h1), '') as integer)        as qa1c_8_2022h1,
        try_cast(nullif(trim(qa1c_9_2022h1), '') as integer)        as qa1c_9_2022h1,
        try_cast(nullif(trim(qa1c_4_2023h1), '') as integer)        as qa1c_4_2023h1,
        try_cast(nullif(trim(qa1c_5_2023h1), '') as integer)        as qa1c_5_2023h1,
        try_cast(nullif(trim(qa1c_6_2023h1), '') as integer)        as qa1c_6_2023h1,
        try_cast(nullif(trim(qa1c_7_2023h1), '') as integer)        as qa1c_7_2023h1,
        try_cast(nullif(trim(qa1c_8_2023h1), '') as integer)        as qa1c_8_2023h1,
        try_cast(nullif(trim(qa1c_9_2023h1), '') as integer)        as qa1c_9_2023h1,
        try_cast(nullif(trim(qa1c_4_2024q3), '') as integer)        as qa1c_4_2024q3,
        try_cast(nullif(trim(qa1c_5_2024q3), '') as integer)        as qa1c_5_2024q3,
        try_cast(nullif(trim(qa1c_6_2024q3), '') as integer)        as qa1c_6_2024q3,
        try_cast(nullif(trim(qa1c_7_2024q3), '') as integer)        as qa1c_7_2024q3,
        try_cast(nullif(trim(qa1c_8_2024q3), '') as integer)        as qa1c_8_2024q3,
        try_cast(nullif(trim(qa1c_9_2024q3), '') as integer)        as qa1c_9_2024q3,

        -- qa2 series
        try_cast(nullif(trim(qa2dec_1_2015h2), '') as integer)      as qa2dec_1_2015h2,
        try_cast(nullif(trim(qa2dec_2_2015h2), '') as integer)      as qa2dec_2_2015h2,
        try_cast(nullif(trim(qa2dec_3_2015h2), '') as integer)      as qa2dec_3_2015h2,
        try_cast(nullif(trim(qa2dec_4_2015h2), '') as integer)      as qa2dec_4_2015h2,
        try_cast(nullif(trim(qa2dec_5_2015h2), '') as integer)      as qa2dec_5_2015h2,
        try_cast(nullif(trim(qa2dec_6_2015h2), '') as integer)      as qa2dec_6_2015h2,
        try_cast(nullif(trim(qa2dec_7_2015h2), '') as integer)      as qa2dec_7_2015h2,
        try_cast(nullif(trim(qa2inc_1_2015h2), '') as integer)      as qa2inc_1_2015h2,
        try_cast(nullif(trim(qa2inc_2_2015h2), '') as integer)      as qa2inc_2_2015h2,
        try_cast(nullif(trim(qa2inc_3_2015h2), '') as integer)      as qa2inc_3_2015h2,
        try_cast(nullif(trim(qa2inc_4_2015h2), '') as integer)      as qa2inc_4_2015h2,
        try_cast(nullif(trim(qa2inc_5_2015h2), '') as integer)      as qa2inc_5_2015h2,
        try_cast(nullif(trim(qa2inc_6_2015h2), '') as integer)      as qa2inc_6_2015h2,
        try_cast(nullif(trim(qa2inc_7_2015h2), '') as integer)      as qa2inc_7_2015h2,
        try_cast(nullif(trim(qa2_1_2016h2), '') as integer)         as qa2_1_2016h2,
        try_cast(nullif(trim(qa2_2_2016h2), '') as integer)         as qa2_2_2016h2,
        try_cast(nullif(trim(qa2_3_2016h2), '') as integer)         as qa2_3_2016h2,
        try_cast(nullif(trim(qa2_4_2016h2), '') as integer)         as qa2_4_2016h2,
        try_cast(nullif(trim(qa2_5_2016h2), '') as integer)         as qa2_5_2016h2,
        try_cast(nullif(trim(qa2_6_2016h2), '') as integer)         as qa2_6_2016h2,
        try_cast(nullif(trim(qa2_7_2016h2), '') as integer)         as qa2_7_2016h2,
        try_cast(nullif(trim(qa2_2017h2), '') as integer)           as qa2_2017h2,
        try_cast(nullif(trim(qa2cat_2017h2), '') as integer)        as qa2cat_2017h2,
        try_cast(nullif(trim(qa2_2018h2), '') as integer)           as qa2_2018h2,
        try_cast(nullif(trim(qa2_a_2019h2), '') as integer)         as qa2_a_2019h2,
        try_cast(nullif(trim(qa2_b_2019h2), '') as integer)         as qa2_b_2019h2,
        try_cast(nullif(trim(qa2_c_2019h2), '') as integer)         as qa2_c_2019h2,
        try_cast(nullif(trim(qa2_d_2019h2), '') as integer)         as qa2_d_2019h2,
        try_cast(nullif(trim(qa2_e_2019h2), '') as integer)         as qa2_e_2019h2,
        try_cast(nullif(trim(qa2_f_2019h2), '') as integer)         as qa2_f_2019h2,
        try_cast(nullif(trim(qa2_g_2019h2), '') as integer)         as qa2_g_2019h2,
        try_cast(nullif(trim(qa2_a_2020h2), '') as integer)         as qa2_a_2020h2,
        try_cast(nullif(trim(qa2_b_2020h2), '') as integer)         as qa2_b_2020h2,
        try_cast(nullif(trim(qa2_c_2020h2), '') as integer)         as qa2_c_2020h2,
        try_cast(nullif(trim(qa2_2019h1), '') as integer)           as qa2_2019h1,
        try_cast(nullif(trim(qa2_2020h1), '') as integer)           as qa2_2020h1,
        try_cast(nullif(trim(qa2_2021h1), '') as integer)           as qa2_2021h1,
        try_cast(nullif(trim(qa2_2021h2), '') as integer)           as qa2_2021h2,
        try_cast(nullif(trim(qa2_2022h1), '') as integer)           as qa2_2022h1,
        try_cast(nullif(trim(qa2_1_2022h2), '') as integer)         as qa2_1_2022h2,
        try_cast(nullif(trim(qa2_2_2022h2), '') as integer)         as qa2_2_2022h2,
        try_cast(nullif(trim(qa2_3_2022h2), '') as integer)         as qa2_3_2022h2,
        try_cast(nullif(trim(qa2_4_2022h2), '') as integer)         as qa2_4_2022h2,
        try_cast(nullif(trim(qa2_5_2022h2), '') as integer)         as qa2_5_2022h2,
        try_cast(nullif(trim(qa2_6_2022h2), '') as integer)         as qa2_6_2022h2,
        try_cast(nullif(trim(qa2_7_2022h2), '') as integer)         as qa2_7_2022h2,
        try_cast(nullif(trim(qa2_2023h1), '') as integer)           as qa2_2023h1,
        try_cast(nullif(trim(qa2_1_2024q2), '') as integer)         as qa2_1_2024q2,
        try_cast(nullif(trim(qa2_2_2024q2), '') as integer)         as qa2_2_2024q2,
        try_cast(nullif(trim(qa2_3_2024q2), '') as integer)         as qa2_3_2024q2,
        try_cast(nullif(trim(qa2_4_2024q2), '') as integer)         as qa2_4_2024q2,
        try_cast(nullif(trim(qa2_5_2024q2), '') as integer)         as qa2_5_2024q2,
        try_cast(nullif(trim(qa2_2024q4), '') as integer)           as qa2_2024q4,
        try_cast(nullif(trim(qa2_2025q2), '') as integer)           as qa2_2025q2,
        try_cast(nullif(trim(qa2_2025q4_a), '') as integer)         as qa2_2025q4_a,
        try_cast(nullif(trim(qa2_2025q4_b), '') as integer)         as qa2_2025q4_b,

        -- qa3 series
        try_cast(nullif(trim(qa3_2017h2), '') as integer)           as qa3_2017h2,
        try_cast(nullif(trim(qa3_a_2021h2), '') as integer)         as qa3_a_2021h2,
        try_cast(nullif(trim(qa3_b_2021h2), '') as integer)         as qa3_b_2021h2,
        try_cast(nullif(trim(qa3_c_2021h2), '') as integer)         as qa3_c_2021h2,
        try_cast(nullif(trim(qa3_c1_2022h2), '') as integer)        as qa3_c1_2022h2,
        try_cast(nullif(trim(qa3_d_2021h2), '') as integer)         as qa3_d_2021h2,
        try_cast(nullif(trim(qa3_e_2021h2), '') as integer)         as qa3_e_2021h2,
        try_cast(nullif(trim(qa3_f_2021h2), '') as integer)         as qa3_f_2021h2,
        try_cast(nullif(trim(qa3_g_2021h2), '') as integer)         as qa3_g_2021h2,
        try_cast(nullif(trim(qa3_2020h2), '') as integer)           as qa3_2020h2,
        try_cast(nullif(trim(qa3_1_2019h1), '') as integer)         as qa3_1_2019h1,
        try_cast(nullif(trim(qa3_2_2019h1), '') as integer)         as qa3_2_2019h1,
        try_cast(nullif(trim(qa3_3_2019h1), '') as integer)         as qa3_3_2019h1,
        try_cast(nullif(trim(qa3_4_2019h1), '') as integer)         as qa3_4_2019h1,
        try_cast(nullif(trim(qa3_1_2020h1), '') as integer)         as qa3_1_2020h1,
        try_cast(nullif(trim(qa3_2_2020h1), '') as integer)         as qa3_2_2020h1,
        try_cast(nullif(trim(qa3_3_2020h1), '') as integer)         as qa3_3_2020h1,
        try_cast(nullif(trim(qa3_4_2020h1), '') as integer)         as qa3_4_2020h1,
        try_cast(nullif(trim(qa3_1_2021h1), '') as integer)         as qa3_1_2021h1,
        try_cast(nullif(trim(qa3_2_2021h1), '') as integer)         as qa3_2_2021h1,
        try_cast(nullif(trim(qa3_3_2021h1), '') as integer)         as qa3_3_2021h1,
        try_cast(nullif(trim(qa3_1_2022h1), '') as integer)         as qa3_1_2022h1,
        try_cast(nullif(trim(qa3_2_2022h1), '') as integer)         as qa3_2_2022h1,
        try_cast(nullif(trim(qa3_3_2022h1), '') as integer)         as qa3_3_2022h1,
        try_cast(nullif(trim(qa3_4_2022h1), '') as integer)         as qa3_4_2022h1,
        try_cast(nullif(trim(qa3_1_2022h2), '') as integer)         as qa3_1_2022h2,
        try_cast(nullif(trim(qa3_2_2022h2), '') as integer)         as qa3_2_2022h2,
        try_cast(nullif(trim(qa3_1_2023h1), '') as integer)         as qa3_1_2023h1,
        try_cast(nullif(trim(qa3_2_2023h1), '') as integer)         as qa3_2_2023h1,
        try_cast(nullif(trim(qa3_3_2023h1), '') as integer)         as qa3_3_2023h1,
        try_cast(nullif(trim(qa3_4_2023h1), '') as integer)         as qa3_4_2023h1,
        try_cast(nullif(trim(qa3_1_2024q3), '') as integer)         as qa3_1_2024q3,
        try_cast(nullif(trim(qa3_2_2024q3), '') as integer)         as qa3_2_2024q3,
        try_cast(nullif(trim(qa3_3_2024q3), '') as integer)         as qa3_3_2024q3,
        try_cast(nullif(trim(qa3_4_2024q3), '') as integer)         as qa3_4_2024q3,
        try_cast(nullif(trim(qa3_2024q4), '') as integer)           as qa3_2024q4,
        try_cast(nullif(trim(qa3_2025q2_a), '') as integer)         as qa3_2025q2_a,
        try_cast(nullif(trim(qa3_2025q2_b), '') as integer)         as qa3_2025q2_b,
        try_cast(nullif(trim(qa3_2025q2_c), '') as integer)         as qa3_2025q2_c,
        try_cast(nullif(trim(qa3_2025q2_d), '') as integer)         as qa3_2025q2_d,
        try_cast(nullif(trim(qa3_2025q2_e), '') as integer)         as qa3_2025q2_e,
        try_cast(nullif(trim(qa3_2025q4_a), '') as integer)         as qa3_2025q4_a,
        try_cast(nullif(trim(qa3_2025q4_b), '') as integer)         as qa3_2025q4_b,

        -- qa4 / qa5 / qa6 series
        try_cast(nullif(trim(qa41a_2014h2), '') as integer)         as qa41a_2014h2,
        try_cast(nullif(trim(qa41b_1_2014h2), '') as integer)       as qa41b_1_2014h2,
        try_cast(nullif(trim(qa41b_2_2014h2), '') as integer)       as qa41b_2_2014h2,
        try_cast(nullif(trim(qa41b_3_2014h2), '') as integer)       as qa41b_3_2014h2,
        try_cast(nullif(trim(qa41b_4_2014h2), '') as integer)       as qa41b_4_2014h2,
        try_cast(nullif(trim(qa41b_5_2014h2), '') as integer)       as qa41b_5_2014h2,
        try_cast(nullif(trim(qa41c_2014h2), '') as integer)         as qa41c_2014h2,
        try_cast(nullif(trim(qa41c_rec_2014h2), '') as integer)     as qa41c_rec_2014h2,
        try_cast(nullif(trim(qa4_1_2024q3), '') as integer)         as qa4_1_2024q3,
        try_cast(nullif(trim(qa4_2_2024q3), '') as integer)         as qa4_2_2024q3,
        try_cast(nullif(trim(qa4_3_2024q3), '') as integer)         as qa4_3_2024q3,
        try_cast(nullif(trim(qa4_4_2024q3), '') as integer)         as qa4_4_2024q3,
        try_cast(nullif(trim(qa4_2024q4), '') as integer)           as qa4_2024q4,
        try_cast(nullif(trim(qa4_2025q4), '') as integer)           as qa4_2025q4,
        try_cast(nullif(trim(qa5_2024q4), '') as integer)           as qa5_2024q4,
        try_cast(nullif(trim(qa6_a_2024q4), '') as integer)         as qa6_a_2024q4,
        try_cast(nullif(trim(qa6_b_2024q4), '') as integer)         as qa6_b_2024q4,
        try_cast(nullif(trim(qa6_c_2024q4), '') as integer)         as qa6_c_2024q4,

        -- qa21 / qa22 series
        try_cast(nullif(trim(qa21_2024q3), '') as integer)          as qa21_2024q3,
        try_cast(nullif(trim(qa22_2024q3), '') as integer)          as qa22_2024q3,

        -- qb series
        try_cast(nullif(trim(qb1_2025q2), '') as integer)           as qb1_2025q2,
        try_cast(nullif(trim(qb1_2025q4_a), '') as integer)         as qb1_2025q4_a,
        try_cast(nullif(trim(qb1_2025q4_b), '') as integer)         as qb1_2025q4_b,
        try_cast(nullif(trim(qb2_2025q2), '') as integer)           as qb2_2025q2,
        try_cast(nullif(trim(qb2_2025q4_a_g3), '') as integer)      as qb2_2025q4_a_g3,
        try_cast(nullif(trim(qb2_2025q4_a_g4), '') as integer)      as qb2_2025q4_a_g4,
        try_cast(nullif(trim(qb2_2025q4_b_g3), '') as integer)      as qb2_2025q4_b_g3,
        try_cast(nullif(trim(qb2_2025q4_b_g4), '') as integer)      as qb2_2025q4_b_g4,

        --------------------------------------------------------------------------
        -- PIPELINE METADATA (from dlt load)
        --------------------------------------------------------------------------
        _dlt_load_id,
        _dlt_id,
        current_timestamp                                           as _dbt_loaded_at

    from source

)

select * from staged